apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis-yaml
    method: from_code
    update: pod_as_code_is_cool
  name: redis-yaml
spec:
  containers:
  - image: redis
    name: redis-yaml
