apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: first-httpd-deploy
  name: first-httpd-deploy
spec:
  replicas: 7
  selector:
    matchLabels:
      app: first-httpd-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: first-httpd-deploy
    spec:
      containers:
        - image: httpd:alpine
          name: httpd
          command: ["/bin/sh", "-c"]
          args: ["sleep 3; exit 0"]
  strategy:
    type: Recreate
